# services:
#   api:
#     build: .
#     ports:
#       -"80:8000"
#     depends_on:
#       - db
#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: 1234
#       MYSQL_DATABASE: oz
#     ports:
#       -"33060:3306"

version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "80:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: mysql+pymysql://root:1234@db:3306/oz

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: oz
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql  # 여기를 붙여쓰세요
  worker:
    build: ./worker
    volumes:
    - . /worker:/app
    depends_on:
      - redis
  redis:
    image: redis:8
   
volumes:
  db_data:  # 이 줄이 services와 같은 레벨(맨 왼쪽)에 있어야 합니다.